# This is a workflow to build the AST Explorer application

name: Build.GraphExplorer

# Controls when the action will run. Triggers the workflow on push or pull request
# events for any branch.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restore Packages for GraphExplorer project
      run: nuget restore "tools\Graph Explorer\GraphExplorer\SocratexGraphExplorerNeoVis.csproj"
     
    - name: Setup msbuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
     
    - name: Build Graph Explorer with MSBuild
      run: msbuild "tools\Graph Explorer\GraphExplorer\SocratexGraphExplorerNeoVis.csproj"
